### ISSUE TITLE
SigFox of nrf52

### ISSUE THREAD

**Issue by prisikarm** [arduino-libraries/SigFox#29]
Hello,
I am trying to run SigFox module connected with nrf52 (Nano 33 BLE), but the library is not compiling 

`C:\Users\PC-User\Documents\Arduino\libraries\Arduino_SigFox_for_MKRFox1200\src\SigFox.cpp: In member function 'int SIGFOXClass::begin()':
C:\Users\PC-User\Documents\Arduino\libraries\Arduino_SigFox_for_MKRFox1200\src\SigFox.cpp:99:13: error: 'arduino::SPIClass {aka class arduino::HardwareSPI}' has no member named 'setDataMode'
   spi_port->setDataMode(SPI_MODE0);
             ^~~~~~~~~~~
C:\Users\PC-User\Documents\Arduino\libraries\Arduino_SigFox_for_MKRFox1200\src\SigFox.cpp:100:13: error: 'arduino::SPIClass {aka class arduino::HardwareSPI}' has no member named 'setBitOrder'
   spi_port->setBitOrder(MSBFIRST);
             ^~~~~~~~~~~
`

Is there a chance that this library will work with any other architectures instead of only SAMD?

**Comment by aentinger** [comment]
No, this library is for the ``MKR FOX 1210` only.
