### ISSUE TITLE
Latest release (1.0.4) does not compile: `arduino::SPIClass {aka class arduino::HardwareSPI}' has no member named 'setDataMode'`

### ISSUE THREAD

**Issue by dvarrel** [arduino-libraries/SigFox#42]
hi,
examples official 1.04 don't compile ( board package 1.8.13 )

dev 1.05 is ok

`error: 'arduino::SPIClass {aka class arduino::HardwareSPI}' has no member named 'setDataMode'
   spi_port->setDataMode(SPI_MODE0);`

**Comment by per1234** [comment]
Thanks @dvarrel I see the bug was fixed a year ago in https://github.com/arduino-libraries/SigFox/pull/32 but never released.

@aentinger @facchinm please make a 1.0.5 release to deliver this critical bug fix to the users.

**Comment by facchinm** [comment]
Fixed by https://github.com/arduino-libraries/SigFox/releases/tag/1.0.5 , thanks for the heads up!
