### ISSUE TITLE
not sending when more then 12Byte

### ISSUE THREAD

**Issue by florianeichin** [arduino-libraries/SigFox#6]
I tried the FirstConfiguration Sample of the Arduino project and noticed, that sending a message works just 1 of 100 tries when the message is more then 12 Byte long. If the message is 12 Byte, it works like a charm.

**Comment by facchinm** [comment]
The Sigfox protocol limits the message size to a maximum of exactly 12 bytes; in fact, the message is always limited to 12 bytes (see https://github.com/arduino-libraries/SigFox/blob/master/src/SigFox.cpp#L136) but it shouldn't hang anything (you'll only receive 12 bytes on the backend).
If you are experiencing any hang could you share the sketch you are using (or a relevant part of it) ? Thanks!

**Comment by floei** [comment]
I experience hangs, when sending everything over 12 byte.  I use the FirstCnfiguration example Sketch threrefore.

**Comment by facchinm** [comment]
Hi @floei , I just pushed version 1.0.3 that should solve the bug you are experiencing. It should be available as an update via Library manager in the next few hours.
Feel free to reopen the issue if it's not fixed for you. Thanks!
